name: absensi_kuli
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.20.2
  google_fonts: ^8.0.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  # TAMBAHAN: Package untuk animasi
  flutter_animate: ^4.5.2 
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

# TAMBAHAN: Konfigurasi untuk membuat logo otomatis
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21